FROM python:3.11-slim

RUN pip install --no-cache-dir \
    dagster==1.8.13 \
    dagster-graphql==1.8.13 \
    dagster-webserver==1.8.13

ENV DAGSTER_HOME=/opt/dagster/dagster_home

WORKDIR /opt/dagster/app
